Add various features to xbian-config

diff --git a/usr/local/sbin/xbian-config b/usr/local/sbin/xbian-config
--- a/usr/local/sbin/xbian-config
+++ b/usr/local/sbin/xbian-config
@@ -1,7 +1,5 @@
 #!/bin/bash
 #TODO: Check if packages are already installed
-#Check if SD card is already resized
-#Ask confirmation before resizesd
 
 if [ ! $(id -u) -eq 0 ]; then
 	echo "This program must be run as root.";
@@ -35,6 +33,122 @@ if [ $(dpkg-query -W -f='${Status}\n' git | grep 'not-installed' | wc -l) -eq 1 
 	exit 0;
 fi
 
+if [ $(dpkg-query -W -f='${Status}\n' wget | grep 'not-installed' | wc -l) -eq 1 ]; then
+	echo "This program requires the wget package: apt-get install wget";
+	exit 0;
+fi
+
+#Select a file or directory
+#$1 = Return value
+#$2 = Previous menu
+#$3 = Title
+#$4 = Path
+#$5 = Only files?
+#$6 = Specific files?
+#$7 = Only file extensions
+filedirselect() {
+
+	IFS=$'\n'
+	ITEMS=($(ls -AlQ $4 | grep ^d | grep -o "\(\".*\"\)"));
+	if [ $5 -eq 1 ]; then
+		if [ $6 -eq 1 ]; then
+			MESSAGE="\nPlease select a *$7 file";
+			ITEMS+=($(ls -AlQ $4 | grep -v ^d | awk '{print $9}' | grep -o "\(\".*\"\)" | grep $7));
+		else
+			MESSAGE="\nPlease select a file";
+			ITEMS+=($(ls -AlQ $4 | grep -v ^d | awk '{print $9}' | grep -o "\(\".*\"\)"));
+		fi
+	else
+		MESSAGE="\nPlease select a directory";
+	fi
+	if [ $4 != "/" ]; then
+		LIST="0%[..]%";
+		N=1;
+	else
+		LIST="";
+		N=0;
+	fi
+	
+	for ITEM in ${ITEMS[@]}
+	do
+		ITEM=$(echo $ITEM | sed -e 's/\ /\_/g' | sed -e 's/\"//g');
+		if [ -d $4$ITEM ]; then
+			LIST="$LIST$N%[$ITEM]%";
+		else
+			LIST="$LIST$N%$ITEM%";
+		fi
+		
+		N=$(($N+1));
+	done
+	NRITEMS=${#ITEMS[@]};
+	if [ $NRITEMS -lt 8 ]; then
+		NRITEMS=8;
+	fi
+	LIST=$(echo \"$LIST\" | awk '{print substr($0,2,length-3)'} | sed -e 's/\_/\ /g');
+	IFS="%";
+	RETURN=$(dialog --no-kill --backtitle "$BACKTITLE" --title "Config > $3" --extra-button --extra-label Select --ok-label Open --cancel-label Return  --menu $MESSAGE 14 60 $NRITEMS $LIST  3>&1 1>&2 2>&3);
+	BUTTON=$?;
+	IFS=" ";
+	case $BUTTON in
+		1)
+			eval $2;
+		;;
+		3)
+			if [ $4 == "/" ]; then
+				SELECTED=$(echo $4${ITEMS[$((RETURN))]} | sed 's/"//g');
+			else
+				SELECTED=$(echo $4${ITEMS[$((RETURN-1))]} | sed 's/"//g');
+			fi
+			if [[ $RETURN -gt 0 || $4 == "/" ]]; then
+				if [[ $5 -eq 1 && -f $SELECTED ]] || [[ $5 -eq 0 && -d $SELECTED ]]; then
+					eval "$1=\"$SELECTED\"";
+				else
+					if [ $4 == "/" ]; then
+						SELECTED=$(echo $4${ITEMS[$((RETURN))]} | sed 's/"//g');
+					else
+						SELECTED=$(echo $4${ITEMS[$((RETURN-1))]} | sed 's/"//g');
+					fi
+					if [ -f "$SELECTED" ]; then
+						eval "$1=\"$SELECTED\"";
+					else
+						filedirselect $1 $2 "$3" "$SELECTED/" $5 $6 $7;
+					fi
+				fi
+			else
+				LASTDIR=$(echo $4 | sed -e 's/\ /\_/g' | rev | cut -f2 -d "/" | rev);
+				if [ -z $LASTDIR ]; then
+					SELECTED="/";
+				else
+					SELECTED=$(eval "echo \"$4\" | sed -e 's/\ /\_/g' | sed -e 's/$LASTDIR\///g' | sed -e 's/\_/\ /g'");
+				fi
+				filedirselect $1 $2 "$3" "$SELECTED" $5 $6 $7;
+			fi
+		;;
+		0)
+		if [[ $RETURN -eq 0 && $4 != "/" ]]; then
+			LASTDIR=$(echo $4 | sed -e 's/\ /\_/g' | rev | cut -f2 -d "/" | rev);
+			if [ -z $LASTDIR ]; then
+				SELECTED="/";
+			else
+				SELECTED=$(eval "echo \"$4\" | sed -e 's/\ /\_/g' | sed -e 's/$LASTDIR\///g' | sed -e 's/\_/\ /g'");
+			fi
+			filedirselect $1 $2 "$3" "$SELECTED" $5 $6 $7;
+		else
+			if [ $4 == "/" ]; then
+				SELECTED=$(echo $4${ITEMS[$((RETURN))]} | sed 's/"//g');
+			else
+				SELECTED=$(echo $4${ITEMS[$((RETURN-1))]} | sed 's/"//g');
+			fi
+			if [ -f "$SELECTED" ]; then
+				eval "$1=\"$SELECTED\"";
+			else
+				filedirselect $1 $2 "$3" "$SELECTED/" $5 $6 $7;
+			fi
+		fi
+		;;
+	esac;
+}
+
 check_rootssh_status() {
 	if [ -f "/etc/ssh/sshd_config" ]; then
 		STATUS=$(cat /etc/ssh/sshd_config | grep PermitRootLogin | grep "yes" | wc -l)
@@ -52,10 +166,20 @@ xbianinfo() {
 }
 
 changesdsize() {
+	dialog --no-kill --backtitle "$BACKTITLE" --title "Config > Settings > Resize SD" --yesno "\n      Are you sure you want to resize you SD card?" 7 60;
+	case "$?" in
+		1)
+			settings;
+			exit;
+		;;
+	esac
+
 	SWAPSIZE=0;
 	SWAPEXISTS=$(fdisk /dev/mmcblk0 -l | grep "swap" | awk '{print $1}' | awk '{print substr($0,length,length+1)}' | wc -l);
-	PART_START=$(parted /dev/mmcblk0 -ms unit s p | grep "^2" | cut -f 2 -d: | awk '{print substr($0,0,length)}')
-	SDEND=$(parted /dev/mmcblk0 -ms unit s p | grep "/dev/" | cut -f 2 -d: | awk '{print substr($0,0,length)}');
+	PART_START=$(parted /dev/mmcblk0 -ms unit s p | grep "^2" | cut -f 2 -d: | awk '{print substr($0,0,length)}' | grep -o "[0-9]*");
+	CPART_START=$PART_START;
+	CPART_END=$(parted /dev/mmcblk0 -ms unit s p | grep "^2" | cut -f 3 -d: | awk '{print substr($0,0,length)}' | grep -o "[0-9]*");
+	SDEND=$(parted /dev/mmcblk0 -ms unit s p | grep "/dev/" | cut -f 2 -d: | awk '{print substr($0,0,length)}' | grep -o "[0-9]*");
 	SDEND=$(($SDEND-1));
 	SDSIZE=$((($SDEND*512)/1024/1024));
 
@@ -75,6 +199,29 @@ changesdsize() {
 	SWAP_START=$(($PART_END+1));
 	SWAP_END=$(($SDEND));
 	
+	if [ $PART_END -gt $SWAP_START ]; then
+		dialog --backtitle "$BACKTITLE" --title "Config > Settings > Resize SD" --ok-label Close --msgbox "\n      There is not enough space to create a swap partition. Aborting." 7 60
+		settings;
+		exit 0;
+	fi
+		
+	if [ $SWAPEXISTS -eq 1 ]; then
+		CSWAP_START=$(parted /dev/mmcblk0 -ms unit s p | grep "^3" | cut -f 2 -d: | awk '{print substr($0,0,length)}' | grep -o "[0-9]*");
+		CSWAP_END=$(parted /dev/mmcblk0 -ms unit s p | grep "^3" | cut -f 3 -d: | awk '{print substr($0,0,length)}' | grep -o "[0-9]*");
+		if [[ $PART_START -eq $CPART_START && $PART_END -eq $CPART_END && $SWAP_START -eq $CSWAP_START && $SWAP_END -eq $CSWAP_END ]]; then
+			dialog --backtitle "$BACKTITLE" --title "Config > Settings > Resize SD" --ok-label Close --msgbox "\n      This SD card is already resized. Aborting." 7 60
+			settings;
+			exit;
+		fi
+	fi
+	
+	echo $PART_START;
+	echo $SDEND;
+	echo $SWAPSIZE;
+	echo $PART_END;
+	echo $SWAP_START;
+	echo $SWAP_END;
+	exit;
 	if [ $DEBUG -eq 0 ]; then
 		if [ $SWAPEXISTS -eq 1 ]; then
 fdisk /dev/mmcblk0 <<EOF
@@ -182,10 +329,10 @@ changetimezone() {
 }
 
 changepass() {
-	PASS=$(dialog --backtitle "$BACKTITLE" --title "Config > Settings > Change password" --ok-label Change --inputbox "Password:" 10 80 3>&1 1>&2 2>&3)
+	PASS=$(dialog --backtitle "$BACKTITLE" --title "Config > Settings > Change password" --ok-label Change --insecure --passwordbox "Password:" 7 80 3>&1 1>&2 2>&3)
 	if [ ! -z $PASS ]; then
 		echo "pi:$PASS" | chpasswd
-		dialog --backtitle "$BACKTITLE" --title "Config > Settings > Change password" --ok-label Close --msgbox "\n\n\n Xbian password succesfully changed" 11 44
+		dialog --backtitle "$BACKTITLE" --title "Config > Settings > Change password" --ok-label Close --msgbox "\n      Xbian password succesfully changed" 7 55
 	fi
 	settings;
 	exit 0
@@ -302,13 +449,78 @@ changeoverclock() {
 	esac
 }
 
+changelicensempg2() {
+	SETTING=$(cat /boot/config.txt | grep 'decode_MPG2');
+	CLICENSE=$(cat /boot/config.txt | grep 'decode_MPG2' | cut -f 2 -d=);
+	if [ ! -z $SETTING ]; then
+		BUTTON="Change";
+		MESSAGE="changed";
+	else
+		BUTTON="Insert";
+		MESSAGE="inserted";
+	fi
+	LICENSE=$(dialog --backtitle "$BACKTITLE" --title "Config > Settings > License MPG2" --ok-label $BUTTON --inputbox "License MPG2:" 7 80 $CLICENSE 3>&1 1>&2 2>&3)
+	if [ ! -z $LICENSE ]; then
+		if [ ! -z $SETTING ]; then
+			CHANGE="sed -i 's/$SETTING/decode_MPG2=$LICENSE/g' /boot/config.txt";
+			eval $CHANGE;
+		else
+			echo "goed";
+			echo "decode_MPG2=$LICENSE" >> /boot/config.txt
+		fi
+		dialog --backtitle "$BACKTITLE" --title "Config > Settings > License MPG2" --ok-label Close --msgbox "\n        MPG2 license succesfully $MESSAGE" 7 55
+	else
+		if [ ! -z $SETTING ]; then
+			CHANGE="sed -i 's/$SETTING//g' /boot/config.txt";
+			eval $CHANGE;
+			dialog --backtitle "$BACKTITLE" --title "Config > Settings > License MPG2" --ok-label Close --msgbox "\n        VC-1 license succesfully deleted" 7 55
+		fi
+	fi
+	grep -v '^$' /boot/config.txt > /boot/config.new
+	mv /boot/config.new /boot/config.txt
+	settings;
+	exit 0
+}
+
+changelicensevc1() {
+	SETTING=$(cat /boot/config.txt | grep 'decode_WVC1');
+	CLICENSE=$(cat /boot/config.txt | grep 'decode_WVC1' | cut -f 2 -d=);
+	if [ ! -z $SETTING ]; then
+		BUTTON="Change";
+		MESSAGE="changed";
+	else
+		BUTTON="Insert";
+		MESSAGE="inserted";
+	fi
+	LICENSE=$(dialog --backtitle "$BACKTITLE" --title "Config > Settings > License VC-1" --ok-label $BUTTON --inputbox "License VC-1:" 7 80 $CLICENSE 3>&1 1>&2 2>&3)
+	if [ ! -z $LICENSE ]; then
+		if [ ! -z $SETTING ]; then
+			CHANGE="sed -i 's/$SETTING/decode_WVC1=$LICENSE/g' /boot/config.txt";
+			eval $CHANGE;
+		else
+			echo "decode_WVC1=$LICENSE" >> /boot/config.txt
+		fi
+		dialog --backtitle "$BACKTITLE" --title "Config > Settings > License VC-1" --ok-label Close --msgbox "\n        VC-1 license succesfully $MESSAGE" 7 55
+	else
+		if [ ! -z $SETTING ]; then
+			CHANGE="sed -i 's/$SETTING//g' /boot/config.txt";
+			eval $CHANGE;
+			dialog --backtitle "$BACKTITLE" --title "Config > Settings > License VC-1" --ok-label Close --msgbox "\n        VC-1 license succesfully deleted" 7 55
+		fi
+	fi
+	grep -v '^$' /boot/config.txt > /boot/config.new
+	mv /boot/config.new /boot/config.txt
+	settings;
+	exit 0
+}
+
 settings() {
 	check_rootssh_status
 	ROOTSSHSTATUS="Enable";
     if [ $DISABLE_ROOTSSH -eq 1 ]; then
         ROOTSSHSTATUS="Disable"
     fi
-	RETURN=$(dialog --backtitle "$BACKTITLE" --title 'Config > Settings' --ok-label Select --cancel-label Return --menu '' 11 80 5 1 "Resize SD       - \"Expand root partition to fill SD card\"" 2 "Change Password - \"Change password for 'xbian' user\"" 3 "Set timezone    - \"Set the default timezone\"" 4 "SSH root login  - \"$ROOTSSHSTATUS SSH root login\"" 5 "Overclocking    - \"Configure overclocking\"" 3>&1 1>&2 2>&3)
+	RETURN=$(dialog --backtitle "$BACKTITLE" --title 'Config > Settings' --ok-label Select --cancel-label Return --menu '' 11 80 7 1 "Resize SD       - \"Expand root partition to fill SD card\"" 2 "Change Password - \"Change password for 'xbian' user\"" 3 "Set timezone    - \"Set the default timezone\"" 4 "SSH root login  - \"$ROOTSSHSTATUS SSH root login\"" 5 "Overclocking    - \"Configure overclocking\"" 6 "License MPG2    - \"Insert, update or delete MPG2 license\"" 7 "License VC-1    - \"Insert, update or delete VC-1 license\"" 3>&1 1>&2 2>&3)
 	case "$RETURN" in
 		1)
 			changesdsize;
@@ -324,6 +536,12 @@ settings() {
 		;;
 		5)
 			changeoverclock;
+		;;
+		6)
+			changelicensempg2
+		;;
+		7)
+			changelicensevc1
 		;;
 		"")
 			mainmenu;
@@ -347,7 +565,8 @@ savepackage() {
 
 	NAME=$(basename $PKGFILE);
 	NAME=${NAME%.*}
-	LOCATION=$(dialog --backtitle "$BACKTITLE" --title "Config > $TITLE > Save" --ok-label Save --inputbox "Location:" 10 80 3>&1 1>&2 2>&3)
+	#LOCATION=$(dialog --backtitle "$BACKTITLE" --title "Config > $TITLE > Save" --ok-label Save --inputbox "Location:" 10 80 3>&1 1>&2 2>&3)
+	filedirselect LOCATION "packages" "Settings > $TITLE > Save" "/home/xbian/" 0 0 " ";
 	if [ $LOCATION != "" ]; then
 		if [ -d $LOCATION ]; then
 			tar -cf "$LOCATION/$NAME.tar" /tmp/xbiancache/* >/dev/nullf
@@ -583,7 +802,8 @@ remotepackages() {
 
 localpackages() {
 	PACKAGELOCATION=2;
-	LOCATION=$(dialog --backtitle "$BACKTITLE" --title "Config > Package" --ok-label Open --inputbox "Location:" 10 80 3>&1 1>&2 2>&3)
+	#LOCATION=$(dialog --backtitle "$BACKTITLE" --title "Config > Package" --ok-label Open --inputbox "Location:" 10 80 3>&1 1>&2 2>&3)
+	filedirselect LOCATION "packages" "Settings > Packages" "/home/xbian/" 1 1 ".tar.gz";
 	if [ ! -z $LOCATION ]; then
 		if [ -f $LOCATION ]; then
 			NAME=$(basename $LOCATION);
